### ISSUE TITLE
[bug] Default environment always loaded, also when var is already defined

### ISSUE THREAD

**Issue by jorritsmit** [dynaconf/dynaconf#558] opened 2021-03-20 19:59 UTC
**Describe the bug**
As i understand from reading the code, the default environment is implemented by adding it to the environment list in build_env_list(). This means, however, that if a change my environment (in my case using from_env) the default settings overwrite the existing settings (again as i understand). This seems like undesirable behavior to me, as i expect default settings to only be set when they are not defined already.

**To Reproduce**
use below config files and perform:
from config.config import settings as base_cfg
cfg = base_cfg.from_env(env2, keep=True).from_env(env1, keep=True)
print(cfg.TEST)
desired result should be False, but is True

2. Having the following config files:

<details>

<summary> Config files </summary>

**/path/settings.toml**

```toml
[default]
TEST = true
[env1]

[env2]
TEST = false
```

</details>

**Comment by rochacbruno** [comment] 2021-03-21 00:06
I think this is a duplicate of https://github.com/rochacbruno/dynaconf/issues/344

**Comment by jorritsmit** [comment] 2021-03-21 00:20
> I think this is related to #344

It is a duplicate indeed I think. My apologies

**Comment by rochacbruno** [comment] 2024-07-08 17:43
This issue will be part of #1157

**Closed by rochacbruno** 2024-07-08 17:43 UTC
Labels: bug, HIGH
