### ISSUE TITLE
Is it possible to read additional settings on demand?

### ISSUE THREAD

**Issue by thmsklngr** [dynaconf/dynaconf#909] opened 2023-03-31 10:26 UTC
Currently I'm writing a bigger application which has the requirement to load additional module specific configuration files whenever this module is called.

I already tried this example:
```python
# conf/module.toml
dynaconf_merge=true
[module_name]
setting_1="val1"
setting_2="val2"
```
```python
>>> from config import settings
>>> settings.load_file(path='conf/module.toml')
```

The values do not show up in `settings`. Well, I may have a wrong understanding of `settings.load_file()`, however, it should be possible to load additional files on demand later on.

Anyone got tips on this?

Regards, Thomas

**Comment by pedro-psb** [comment] 2023-03-31 19:25
This works here with 3.1.12:

```toml
# ./conf/module.toml
message="loaded from module (on-demand)"
```

```python
# running python from ./
>>> from dynaconf import Dynaconf
>>> s = Dynaconf()
>>> s.load_file(path="conf/module.toml")
>>> s.message
'loaded from module (on-demand)'
```

Maybe you could give more context so I can try to reproduce it here, like how are you trying to access it, how is your `settings` configured and how is your project structure.

**Comment by mosesontheweb** [comment] 2023-03-31 20:04
Well, in this case you initialize an empty settings object `s` and then load a configuration file. In my case I already loaded the default files and then I try to load additional settings.

Anyway, since `dynaconf` is based on `python-box` I'd rather rely on the second one, there's not much benefit for me in `dynaconf`.

**Comment by pedro-psb** [comment] 2023-03-31 20:19
The following works as well:

```python
$ ls
./settings.toml
./conf/module.toml

$ python3
>>> from dynaconf import Dynaconf as D
>>> s = D(settings_file="settings.toml")
>>> s.username
'Name from settings'
>>> s.load_file("conf/module.toml")
>>> s.username
'from module.toml (on-demand)'
```
I guess this may be related to paths or getting fresh values.

**Comment by thmsklngr** [comment] 2023-04-01 15:52
I tried as suggested but it worked only with this small script:

```python
>>> from dynaconf import Dynaconf
>>> s = Dynaconf()
>>> s.load_file('conf/settings.toml')
>>> s.load_file('conf/module.toml')
```

When working with `settings_file` the second import with `load_file` does not have an effect, the content is neither loaded nor merged (even though I set `dynaconf_merge=true` at the beginning of the .toml file).

**Comment by pedro-psb** [comment] 2023-04-06 22:07
Sorry, I'm really not being able to reproduce this behaviour here.
I understand you said you may not need to use dynaconf anymore, but if you are still available, try following this template:

</br>

Steps to reproduce the behavior:

1. Having the following folder structure



<details>
<summary> Project structure </summary>

```bash

# /path/
# ...../folder/...
# please provide your folder structure here

```
</details>

2. Having the following config files:



<details>
<summary> Config files </summary>

**/path/.env**
```bash
Your .env content here
```

and

**/path/settings.toml**
```toml
[default]
```

</details>

3. Having the following app code:

<details>
<summary> Code </summary>

**/path/src/app.py**
```python
from dynaconf import settings
...
```

</details>

4. Executing under the following environment

<details>
<summary> Execution </summary>

```bash
# other commands and details?
# virtualenv activation?

$ python /path/src/app.py
```

</details>

**Comment by pedro-psb** [comment] 2023-04-13 17:46
@SonGokussj4 Thanks for the good sample code.

This is related to paths, as I thought. Here are some useful facts I found out:
- `load_file` uses `_root_path` (internal root path value) as a reference for where to start looking
- `_root_path` can be defined explicitly with `ROOT_PATH_FOR_DYNACONF`. Note that it is relative to `cwd` or absolute.
- If `ROOT_PATH_FOR_DYNACONF` is not defined explicitly, `_root_path` will fallback:
	- *dir of first loaded file* > *cwd*


So, in the first example, as `ROOT_PATH_FOR_DYNACONF` was not defined explicitly, it was using the *first loaded file dir* as a reference (`app/config/`, as you pointed out in your example). If you set `root_path="."` it shall work.

```diff
# app/config/dynaconfig.py
from dynaconf import Dynaconf

settings = Dynaconf(
    envvar_prefix="MYAPP",
    settings_files=['app/config/default_settings.yaml'],
    merge_enabled=True,
+++ root_path="."
)
```

I guess that the default behaviour for`load_file` when `ROOT_PATH_FOR_DYNACONF` is not defined should be to use `cwd` (in fact, this seems to be the intention in the codebase).

I'll do a PR to address this.

**Comment by pedro-psb** [comment] 2023-04-13 19:21
@rochacbruno I was thinking about it, although I would expect it to fallback to `cwd` in this case, this will be inconsistent with the rest of the loading strategies (the `includes` option, for example, which uses the last loaded file path assuming all configs will be in the same dir). Also, it may break code that relies on this behaviour.

Should we really change this? Some alternatives
- Explain it better in the docs (in [`configuration#root_path`](https://www.dynaconf.com/configuration/#root_path) and in [`advanced#programmatically-loading-a-setting-file`](https://www.dynaconf.com/advanced/#programmatically-loading-a-settings-file)).
- Add `file_finder` param in `load_file` to define custom loading strategy (related to the proposal of [flexible loading strategies](https://github.com/dynaconf/dynaconf/issues/832#issuecomment-1451987318) for v4). In this case, would be nice to write a more detailed specs on this so it can be implemented gradually without breaks.

**Comment by rochacbruno** [comment] 2023-04-18 14:08
@pedro-psb I like it, but if we are going to handle the expansion we have to do it on the find_file function so it can be aplied everywhere

**Closed** 2023-04-27 22:16 UTC
Labels: bug, Docs
