### ISSUE TITLE
[bug] path is not written to config.py

### ISSUE THREAD

**Issue by thmsklngr** [dynaconf/dynaconf#908] opened 2023-03-31 09:56 UTC
**Describe the bug**
I initialized a new configuration with this command:
`dynaconf init -p conf -s SECRET=qwertz123 -v username=Godot`

All files are written correctly to its destinations, however, `config.py` still holds the default values:
```python

from dynaconf import Dynaconf

settings = Dynaconf(
    envvar_prefix="DYNACONF",
    settings_files=['settings.toml', '.secrets.toml'],
)

# `envvar_prefix` = export envvars with `export DYNACONF_FOO=bar`.
# `settings_files` = Load these files in the order.
```

**To Reproduce**

1. Having the following folder structure

<details>
<summary> Project structure </summary>

```bash
├── .env
├── .gitignore
├── .pdm.toml
├── conf
│  ├── .gitignore
│  ├── .secrets.toml
│  └── settings.toml
├── config.py
```
</details>

2. Having the following config files:

<details>
<summary> Config files </summary>

**.env**
```bash
DYNACONF_DATABASE_SERVER=localhost
```

and

**/path/settings.toml**
```toml
username="Godot"

```

</details>

3. Having the following app code:

<details>
<summary> Code </summary>

**/path/src/app.py**
```python
from dynaconf import settings
...
```

</details>

4. Executing under the following environment

<details>
<summary> Execution </summary>

Run directly in dynamic interpreter. (import ...)

</details>

**Expected behavior**
I'd rather expect this whenever I specify an additional path:
```python

from dynaconf import Dynaconf

settings = Dynaconf(
    envvar_prefix="DYNACONF",
    settings_files=['conf/settings.toml', 'conf/.secrets.toml'],
)

# `envvar_prefix` = export envvars with `export DYNACONF_FOO=bar`.
# `settings_files` = Load these files in the order.
```

**Environment (please complete the following information):**
 - OS: Manjaro Linux 22.0.5
 - Dynaconf Version 3.1.12
 - Frameworks in use None

**Additional context**
None.

**Comment by pedro-psb** [comment] 2023-03-31 17:26
I think that the intended behaviour for this option is to define the root of the project and place everything there (being the root like the place where your `.git` is).

If this is true, then the option to define the *relative path of the setting files* is just not implemented. Also, this would mean that we have another bug which is that `config.py` is placed where your `cwd` is, not in the path provided by `--path`.

This is an assumption, but that's how I think it is intended to work, currently:

```bash
$ pwd
/home/user/

$ ls workspace/myproject
.git/
app.py

$ dynaconf init -p workspace/myproject -s SECRET=qwertz123 -v username=Godot
$ ls workspace/myproject
.git/
app.py
+ config.py # currently this would be wrongly placed in ~/config.py
+ settings.toml
+ .secrets.toml
+ .gitignore
```

---

### Proposal

In any case, I think we might have two commands:
- one for setting the `root` of the project, mostly to define where `.gitignore` and `config.py` will be placed. **
- another to set the relative settings path, which would properly update the path in `config.py`, as you'd mentioned.

  ** The concept of *root of the project* can be ambiguous. I've said here that is where `.gitignore` is placed, but this may refer to a `/src` in a *src layout*, in which case the `.gitignore` would be misplaced inside it.

  Maybe the placement of `.gitignore` should use the strategy of trying to find the first folder which have `.git/` starting from `$PWD` until reaching`$HOME`.*

### Usage sample:

Case 1) `project_root` == `.git/` (same base path)

```bash
$ ls
.git/
app.py

$ dynaconf init --settings-path conf -s secret=qwertz123 -v username=Godot
$ ls
.git/
app.py
+ conf/
+     settings.toml
+     .secrets.toml
+ config.py # containing settings_file=["conf/settings.toml", "conf/.secrets.toml"]
+ .gitignore
```

Case 2) `project_root` != `.git/` (different base path)

```bash
$ ls
.git/
src/
    app.py

$ dynaconf init -p src --settings-path conf -s secret=qwertz123 -v username=Godot
$ ls
.git/
src/
    app.py
+     conf/
+         settings.toml
+         .secrets.toml
+     config.py
+ .gitignore
```

**Comment by mosesontheweb** [comment] 2023-03-31 18:27
I read through the manuals a couple times and I guess that the option `root_path` is the option on how to point dynaconf to its configuration files. But I wonder why it is not written to `config.py` if this option is given.

Regards, Thomas

**Comment by pedro-psb** [comment] 2023-03-31 19:42
I think this is a little confusing too, I am just trying to figure out what makes sense to me.

I'm not sure if you meant that, but I guess the *project root* that the `--path` help mentions does not refer to the same concept as the [`root_path`](https://www.dynaconf.com/configuration/#root_path) config option. For me, `--path` here is a cli specific option to tell where to place the files, and `root_path` is indeed what you've described.

I guess @rochacbruno can give some clarification on this subject, I might be getting off-road here.

**Comment by rochacbruno** [comment] 2024-07-08 17:58
on #1154 we are discussing deprecation of the `init` command, if that is the case then we must close this issue

**Comment by rochacbruno** [comment] 2024-07-12 15:44
#1163

**Closed by rochacbruno** 2024-07-12 15:44 UTC
Labels: bug
